/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CourseRouteImport } from './routes/course'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ChapterChapterIdRouteImport } from './routes/chapter.$chapterId'
import { Route as CourseIndexRouteImport } from './routes/course.index'
import { Route as CoursePartIdRouteImport } from './routes/course.$partId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseRoute = CourseRouteImport.update({
  id: '/course',
  path: '/course',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ChapterChapterIdRoute = ChapterChapterIdRouteImport.update({
  id: '/chapter/$chapterId',
  path: '/chapter/$chapterId',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseIndexRoute = CourseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CourseRoute,
} as any)
const CoursePartIdRoute = CoursePartIdRouteImport.update({
  id: '/$partId',
  path: '/$partId',
  getParentRoute: () => CourseRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/course': typeof CourseRouteWithChildren
  '/progress': typeof ProgressRoute
  '/resources': typeof ResourcesRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/chapter/$chapterId': typeof ChapterChapterIdRoute
  '/course/$partId': typeof CoursePartIdRoute
  '/course/': typeof CourseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/progress': typeof ProgressRoute
  '/resources': typeof ResourcesRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/chapter/$chapterId': typeof ChapterChapterIdRoute
  '/course/$partId': typeof CoursePartIdRoute
  '/course': typeof CourseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/course': typeof CourseRouteWithChildren
  '/progress': typeof ProgressRoute
  '/resources': typeof ResourcesRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/chapter/$chapterId': typeof ChapterChapterIdRoute
  '/course/$partId': typeof CoursePartIdRoute
  '/course/': typeof CourseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/course'
    | '/progress'
    | '/resources'
    | '/search'
    | '/settings'
    | '/chapter/$chapterId'
    | '/course/$partId'
    | '/course/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/progress'
    | '/resources'
    | '/search'
    | '/settings'
    | '/chapter/$chapterId'
    | '/course/$partId'
    | '/course'
  id:
    | '__root__'
    | '/'
    | '/course'
    | '/progress'
    | '/resources'
    | '/search'
    | '/settings'
    | '/chapter/$chapterId'
    | '/course/$partId'
    | '/course/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CourseRoute: typeof CourseRouteWithChildren
  ProgressRoute: typeof ProgressRoute
  ResourcesRoute: typeof ResourcesRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  ChapterChapterIdRoute: typeof ChapterChapterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course': {
      id: '/course'
      path: '/course'
      fullPath: '/course'
      preLoaderRoute: typeof CourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapter/$chapterId': {
      id: '/chapter/$chapterId'
      path: '/chapter/$chapterId'
      fullPath: '/chapter/$chapterId'
      preLoaderRoute: typeof ChapterChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/': {
      id: '/course/'
      path: '/'
      fullPath: '/course/'
      preLoaderRoute: typeof CourseIndexRouteImport
      parentRoute: typeof CourseRoute
    }
    '/course/$partId': {
      id: '/course/$partId'
      path: '/$partId'
      fullPath: '/course/$partId'
      preLoaderRoute: typeof CoursePartIdRouteImport
      parentRoute: typeof CourseRoute
    }
  }
}

interface CourseRouteChildren {
  CoursePartIdRoute: typeof CoursePartIdRoute
  CourseIndexRoute: typeof CourseIndexRoute
}

const CourseRouteChildren: CourseRouteChildren = {
  CoursePartIdRoute: CoursePartIdRoute,
  CourseIndexRoute: CourseIndexRoute,
}

const CourseRouteWithChildren =
  CourseRoute._addFileChildren(CourseRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CourseRoute: CourseRouteWithChildren,
  ProgressRoute: ProgressRoute,
  ResourcesRoute: ResourcesRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  ChapterChapterIdRoute: ChapterChapterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
